"""Phishing URL analysis routes."""
import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, Field

from app import db
from app.core.deps import client_ip, require_privilege_at_least
from app.phishing.analyzer import analyze_and_store, validate_url_format
from app.pipeline import pipeline

router = APIRouter()


class PhishingRequest(BaseModel):
    url: str = Field(min_length=2, max_length=2048)


@router.post("/analyze")
def analyze_url(body: PhishingRequest, request: Request,
                _payload: dict = Depends(require_privilege_at_least("SOC_ANALYST"))) -> dict:
    """Analyze a URL and, on a MALICIOUS verdict, feed the detection pipeline so
    the URL becomes a real alert + incident (with MITRE T1566 evidence)."""
    validation_error = validate_url_format(body.url)
    if validation_error:
        raise HTTPException(status_code=422, detail=validation_error)
    result = analyze_and_store(body.url, scanner_ip=client_ip(request))
    db.log_audit(actor=_payload["sub"], role=_payload["role"], action="phishing.analyze",
                 result="SUCCESS", ip=client_ip(request),
                 detail={"url": body.url, "verdict": result.get("verdict"),
                         "risk_score": result.get("risk_score")})
    if result.get("verdict") == "MALICIOUS":
        _correlate_malicious(body.url, result, scanner_ip=client_ip(request))
    return result


def _correlate_malicious(url: str, result: dict, scanner_ip: str = "") -> None:
    """Feed a real phishing.detected event into the pipeline.

    This is a real detection generated by real analysis — not simulated data.
    It flows through the normal detection path (rule -> alert -> incident).
    """
    now = datetime.now(timezone.utc).isoformat()
    pipeline.ingest({
        "event_id": f"phish_{uuid.uuid4().hex[:12]}",
        "ts": now,
        "source": "phishing-analyzer",
        "source_type": "integration",
        "event_type": "phishing.detected",
        "category": "phishing",
        "severity": result.get("verdict_confidence_severity", "high"),
        "host": "",
        "environment": "",
        "details": {
            "url": url,
            "host": result.get("host", ""),
            "verdict": "MALICIOUS",
            "risk_score": result.get("risk_score", 0),
            "confidence": result.get("confidence", 0.0),
            "reasons": result.get("reasons", []),
            "scanner_ip": scanner_ip,
            "evidence": result.get("reasons", []),
        },
    }, source="phishing-analyzer")


@router.get("/scans")
def list_scans(_payload: dict = Depends(require_privilege_at_least("SOC_ANALYST"))) -> dict:
    return {"items": db.list_phishing()}
